Repository FRONTENDBOOTCAMP-13th/Final-09-MIRINE, pull requests merged in 2025-07, with the labels that each got.

#24 🔧 build: 폴더 구조 초기 설정
  public/font/.gitkeep
  src/api/dbinit/.gitkeep
  src/app/(auth)/login/page.tsx
  src/app/(auth)/signup/page.tsx
  src/app/aroma-shooter/page.tsx
  src/app/error.tsx
  src/app/layout.tsx
  src/app/loading.tsx
  src/app/mirine-test/page.tsx
  src/app/mirine/page.tsx
  src/app/mypage/layout.tsx
  src/app/mypage/mirine-test-result/page.tsx
  src/app/mypage/myreviews/page.tsx
  src/app/mypage/orders/page.tsx
  src/app/mypage/page.tsx
  src/app/mypage/profile/page.tsx
  src/app/mypage/returns/page.tsx
  src/app/mypage/shipping/page.tsx
  src/app/mypage/wishlist/page.tsx
  src/app/not-found.tsx
  src/app/perfumes/[id]/page.tsx
  src/app/perfumes/page.tsx
  src/app/reviews/page.tsx
  src/app/shopping-cart/page.tsx
  src/assets/.gitkeep
  src/components/MypageAside/MypageAside.tsx
  src/components/MypageAside/mypageAside.module.css
  src/components/common/Footer/Footer.tsx
  src/components/common/Footer/footer.module.css
  src/components/common/Header/Header.tsx
  src/components/common/Header/header.module.css
  src/hooks/.gitkeep
  src/lib/.gitkeep
  src/store/.gitkeep
  src/types/.gitkeep
Labels: 🔴 P1: High, 😱 hard, 💻 frontend, ⚙️setting

#28 Setting/initialize css variables
  public/font/.gitkeep
  public/font/SUIT-Variable-woff2/SUIT-Variable.woff2
  src/app/globals.css
  src/app/layout.tsx
  src/app/reset.css
Labels: 🔴 P1: High, 🦁 chore, 💻 frontend, 😊 easy, 👁️ a11y

#32 Feature/header
  public/header/Icons.svg
  public/header/logo.svg
  src/app/globals.css
  src/app/page.module.css
  src/app/reset.css
  src/components/common/Header/Header.tsx
  src/components/common/Header/header.module.css
Labels: 🔴 P1: High, 😐 medium, ✨ feature, 🎨 UI/UX, 💻 frontend

#38 Feature/perfumes
  public/icon/Icon-chevron-down-xs.svg
  public/icon/Icon-chevron-up-xs.svg
  public/icon/Icon-like-off-lg.svg
  public/icon/Icon-like-off-sm.svg
  public/icon/Icon-like-on-lg.svg
  public/icon/Icon-like-on-sm.svg
  public/icon/Icon-search.svg
  src/app/globals.css
  src/app/perfumes/page.module.css
  src/app/perfumes/page.tsx
  src/components/perfumes/DetailSearchToggleButton/DetailSearchToggleButton.tsx
  src/components/perfumes/DetailSearchToggleButton/detailSearchToggleButton.module.css
  src/components/perfumes/FilterButton/FilterButton.tsx
  src/components/perfumes/FilterButton/filterButton.module.css
  src/components/perfumes/FilterSection/FilterSection.tsx
  src/components/perfumes/FilterSection/filterSection.module.css
  src/components/perfumes/PerfumeItem/PerfumeItem.tsx
  src/components/perfumes/PerfumeItem/perfumeItem.module.css
  src/components/perfumes/SearchBar/SearchBar.tsx
  src/components/perfumes/SearchBar/searchBar.module.css
Labels: 🔴 P1: High, 😐 medium, ✨ feature, 🎨 UI/UX, 💻 frontend

#37 feature/shopping-cart
  src/app/shopping-cart/page.module.css
  src/app/shopping-cart/page.tsx
  src/components/shopping-cart/CartWithItem/CartWithItems.tsx
  src/components/shopping-cart/CartWithItem/cartWithItems.module.css
  src/components/shopping-cart/EmptyCart/EmptyCart.tsx
  src/components/shopping-cart/EmptyCart/emptyCart.module.css
  src/components/shopping-cart/ProductItem.tsx
Labels: 🔴 P1: High, ✨ feature, 😱 hard, 🎨 UI/UX, 💻 frontend

#41 💄 design: feature/test
  public/image/test-plane.svg
  public/image/test-start.svg
  src/app/mirine-test/page.tsx
  src/app/shopping-cart/page.tsx
  src/components/MinineTest/Header/Header.tsx
  src/components/MinineTest/Header/header.module.css
  src/components/MinineTest/ResultPage/PerfumeResult.tsx
  src/components/MinineTest/ResultPage/ResultPage.tsx
  src/components/MinineTest/ResultPage/resultPage.module.css
  src/components/MinineTest/StartPage/TestStartPage.tsx
  src/components/MinineTest/StartPage/testStartPage.module.css
  src/components/MinineTest/TestPage/MirineTest.tsx
  src/components/MinineTest/TestPage/mirineTest.module.css
  src/components/ShoppingCart/CartWithItem/CartWithItems.tsx
  src/components/ShoppingCart/CartWithItem/cartWithItems.module.css
  src/components/ShoppingCart/EmptyCart/EmptyCart.tsx
  src/components/ShoppingCart/EmptyCart/emptyCart.module.css
  src/components/ShoppingCart/ProductItem.tsx
  src/components/common/Header/Header.tsx
Labels: 🔴 P1: High, ✨ feature, 🎨 UI/UX, 💻 frontend, 😊 easy

#40 ✨ feat:feature/easy login
  package-lock.json
  package.json
  public/login/구글_로그인.svg
  public/login/네이버_로그인.svg
  public/login/카카오_로그인.svg
  src/api/dbinit/firebase.ts
  src/app/(auth)/login/login.module.css
  src/app/(auth)/login/page.tsx
  src/app/globals.css
  src/app/naverLoginCallback/page.tsx
  src/components/common/Header/Header.tsx
  src/components/common/Header/header.module.css
Labels: 😐 medium, ✨ feature, 🟢 P3: Medium, 💾 database, 🔗 API

#45 🐛 fix: 버튼 종결태그 오타 수정
  src/components/common/Header/Header.tsx
Labels: 🔴 P1: High, 🐛 bug, 💻 frontend, 😊 easy

#50 feature/test
  public/icon/Icon-kakao.svg
  public/icon/Icon-link5.svg
  src/components/MinineTest/Header/Header.tsx
  src/components/MinineTest/ResultPage/PerfumeResult.tsx
  src/components/MinineTest/ResultPage/ResultPage.tsx
  src/components/MinineTest/ResultPage/perfumeResult.module.css
  src/components/MinineTest/ResultPage/resultPage.module.css
Labels: 😐 medium, ✨ feature, 🟢 P3: Medium, 🎨 UI/UX

#53 Feature/review-list
  src/app/reviews/page.tsx
  src/components/Review/List/List.tsx
  src/components/Review/List/list.module.css
  src/components/Review/ReviewCommon.tsx
  src/components/Review/UserInfo/NameDateTime.tsx
  src/components/Review/UserInfo/nameDateTime.module.css
  src/components/Review/View/View.tsx
  src/components/Review/reviewCommon.module.css
Labels: 😐 medium, 🟢 P3: Medium, 🎨 UI/UX, 💻 frontend

#54 feature/review-photo
  public/image/perfume1.svg
  src/app/reviews/page.tsx
  src/components/Review/Photo/Photo.tsx
  src/components/Review/Photo/photo.module.css
Labels: 😐 medium, ✨ feature, 🟢 P3: Medium, 🎨 UI/UX, 💻 frontend

#60 💄 style: 리뷰 마크업 수정
  src/components/Review/ReviewCommon.tsx
  src/components/Review/reviewCommon.module.css
Labels: 🎨 UI/UX, 💻 frontend, 🟣 P5: Low, 😊 easy

#61 ✨ feat: 미리내 상세 페이지
  public/image/detail-page.svg
  src/app/perfumes/[id]/page.tsx
  src/components/Mirine/Button/MirineButton.tsx
  src/components/Mirine/Button/mirineButton.module.css
  src/components/Mirine/MirineDetailPage/DetailPage.tsx
  src/components/Mirine/MirineDetailPage/detailPage.module.css
Labels: 🔴 P1: High, 😐 medium, ✨ feature, 🎨 UI/UX, 💻 frontend

#62 💄 style: 리뷰 버튼 및 마크업 수정
  src/app/perfumes/[id]/page.tsx
  src/components/Review/ReviewCommon.tsx
  src/components/Review/reviewCommon.module.css
Labels: 😐 medium, 🟡 P2: Medium-High, ✨ feature, 🎨 UI/UX, 💻 frontend

#59 ✨ feat:Feature/signup
  src/api/firebase/firebase.ts
  src/app/(auth)/login/page.tsx
  src/app/(auth)/signup/page.tsx
  src/app/(auth)/signup/signup.module.css
Labels: 😐 medium, 🟡 P2: Medium-High, ✨ feature, 💾 database, 💻 frontend, 🔗 API

#63 Chore/db initial data
  src/api/dbinit/team/data.js
  src/api/dbinit/team/uploadFiles/perfume1.webp
  src/api/dbinit/team/uploadFiles/perfume2.webp
  src/api/dbinit/team/uploadFiles/perfume3.webp
  src/api/dbinit/team/uploadFiles/perfume4.webp
  src/app/api/perfumes/route.ts
  src/types/like.ts
  src/types/mirineTest.ts
  src/types/order.ts
  src/types/perfume.ts
  src/types/review.ts
  src/types/user.ts
  src/types/userInfo.ts
Labels: 🔴 P1: High, 🦁 chore, 😱 hard, 💾 database

#67 Feature/initialize zustand
  package-lock.json
  package.json
  src/store/mirineStore.ts
  src/store/shoppingCartStore.ts
  src/store/userStore.ts
Labels: 🟡 P2: Medium-High, ✨ feature, 💻 frontend, 😊 easy

#69 ✨ feat: 서버 액션 1차 구현
  src/lib/action.ts
Labels: 🔴 P1: High, ✨ feature, 😱 hard, 🔗 API

#88 Feature/server action
  src/api/dbinit/team/data.js
  src/app/devtest/actiontest/page.tsx
  src/app/devtest/actiontest/postMirineTest/MirineTestEx.tsx
  src/app/devtest/actiontest/postMirineTest/PostMirineTestForm.tsx
  src/app/devtest/actiontest/postMirineTest/page.tsx
  src/app/devtest/actiontest/postOrder/PostOrderForm.tsx
  src/app/devtest/actiontest/postOrder/page.tsx
  src/app/devtest/actiontest/postUser/page.tsx
  src/app/devtest/gettest/page.tsx
  src/app/devtest/page.tsx
  src/components/Login/LoginForm.tsx
  src/lib/action.ts
  src/lib/clientFunction.ts
  src/lib/function.ts
  src/types/api.ts
  src/types/type.ts
Labels: 🔴 P1: High, ✅ test, ✨ feature, 😱 hard, 🔗 API

#94 Feature/profile-page
  public/icon/Icon-right-prev.svg
  src/app/mypage/profile/page.tsx
  src/components/MypageAside/MypageAside.tsx
  src/components/MypageAside/ProfileInfo/ProfileInfo.tsx
  src/components/MypageAside/ProfileInfo/profileInfo.module.css
  src/components/MypageAside/SaveButton/SaveButton.tsx
  src/components/MypageAside/SaveButton/saveButton.module.css
  src/components/MypageAside/mypageAside.module.css
Labels: 😐 medium, 🟡 P2: Medium-High, ✨ feature, 🎨 UI/UX, 💻 frontend

#99 Feature/my-review
  src/app/mypage/myreviews/page.tsx
  src/components/MypageAside/MyReview/Buttons/DeleteBtn.tsx
  src/components/MypageAside/MyReview/Buttons/DetailBtn.tsx
  src/components/MypageAside/MyReview/Buttons/EditBtn.tsx
  src/components/MypageAside/MyReview/Buttons/ReviewWriteBtn.tsx
  src/components/MypageAside/MyReview/Buttons/deleteBtn.module.css
  src/components/MypageAside/MyReview/Buttons/detailBtn.module.css
  src/components/MypageAside/MyReview/Buttons/editBtn.module.css
  src/components/MypageAside/MyReview/Buttons/reviewWriteBtn.module.css
  src/components/MypageAside/MyReview/MyReview.tsx
  src/components/MypageAside/MyReview/MyReviewList/MyReviewList.tsx
  src/components/MypageAside/MyReview/MyReviewList/ReviewItem/ReviewItem.tsx
  src/components/MypageAside/MyReview/MyReviewList/ReviewItem/reviewItem.module.css
  src/components/MypageAside/MyReview/MyReviewList/myReviewList.module.css
  src/components/MypageAside/MyReview/MyReviewWriteList/MyReviewWriteList.tsx
  src/components/MypageAside/MyReview/MyReviewWriteList/myReviewWriteList.module.css
  src/components/MypageAside/MyReview/myReview.module.css
  src/components/MypageAside/ReviewWriteEdit/Button/Cancel/CancelBtn.tsx
  src/components/MypageAside/ReviewWriteEdit/Button/Cancel/cancelBtn.module.css
  src/components/MypageAside/ReviewWriteEdit/Button/Register/RegisterBtn.tsx
  src/components/MypageAside/ReviewWriteEdit/Button/Register/registerBtn.module.css
  src/components/MypageAside/ReviewWriteEdit/ReviewWriteEdit.tsx
  src/components/MypageAside/ReviewWriteEdit/reviewWriteEdit.module.css
  src/components/Review/List/List.tsx
  src/components/Review/UserInfo/NameDateTime.tsx
  src/components/Review/UserInfo/nameDateTime.module.css
Labels: 😐 medium, 🟡 P2: Medium-High, ✨ feature, 🎨 UI/UX, 💻 frontend

#98 Bugfix/loginpage
  src/app/(auth)/login/page.tsx
  src/app/(auth)/signup/page.tsx
  src/components/Login/LoginForm.tsx
  src/components/SignUp/SignUpForm.tsx
  src/components/SignUp/signupform.module.css
Labels: 😐 medium, 🟡 P2: Medium-High, 🛠️ enhancement, 💾 database, 🐛 bug, 💻 frontend, 🔗 API

#100 Feature/mypage-review
  src/app/mypage/myreviews/page.tsx
  src/components/MypageAside/ReviewWriteEdit/Button/Cancel/CancelBtn.tsx
  src/components/MypageAside/ReviewWriteEdit/Button/Cancel/cancelBtn.module.css
  src/components/MypageAside/ReviewWriteEdit/Button/Register/RegisterBtn.tsx
  src/components/MypageAside/ReviewWriteEdit/Button/Register/registerBtn.module.css
  src/components/MypageAside/ReviewWriteEdit/ReviewWriteEdit.tsx
  src/components/MypageAside/ReviewWriteEdit/reviewWriteEdit.module.css
Labels: ✨ feature, 🎨 UI/UX, 🔵 P4: Medium-Low, 💻 frontend, 😊 easy

#104 💄 style: header높이 변경에 따른 body최소 높이 수치 수정
  src/app/globals.css
Labels: 🎨 UI/UX, 🔵 P4: Medium-Low, ♻️ refactor, 💻 frontend, 😊 easy, ⚙️setting
