Repository FRONTENDBOOTCAMP-13th/Final-09-MIRINE, pull requests merged in 2025-08, with the labels that each got.

#107 Feature/home
  package-lock.json
  package.json
  public/home/aroma-shooter2.webp
  public/home/aroma-shooter3.webp
  public/home/main-visual-slide-1.webp
  public/home/mirineshop.webp
  public/home/perfumeshop.webp
  src/app/layout.tsx
  src/app/page.module.css
  src/app/page.tsx
  src/components/Home/AromaShooter.tsx
  src/components/Home/FindScent.tsx
  src/components/Home/MainVisualSlide.tsx
  src/components/Home/MirineShop.tsx
  src/components/Home/PerfumeShop.tsx
  src/components/Home/ReviewSlide.tsx
  src/components/Home/aromaShooter.module.css
  src/components/Home/findScent.module.css
  src/components/Home/mainVisualSlide.module.css
  src/components/Home/mirineShop.module.css
  src/components/Home/perfumeShop.module.css
  src/components/Home/reviewSlide.module.css
  src/components/ui/Container.tsx
  src/components/ui/container.module.css
Labels: 😐 medium, 🟡 P2: Medium-High, ✨ feature, 🎨 UI/UX, 💻 frontend

#106 Feature/review-edit
  src/app/mypage/myreviews/page.tsx
  src/app/mypage/page.tsx
  src/app/mypage/profile/page.tsx
  src/app/perfumes/[id]/page.tsx
  src/app/reviews/write/page.tsx
  src/components/MypageAside/MyReview/Buttons/ReviewWriteBtn.tsx
  src/components/MypageAside/MyReview/Buttons/deleteBtn.module.css
  src/components/MypageAside/MyReview/Buttons/detailBtn.module.css
  src/components/MypageAside/MyReview/Buttons/editBtn.module.css
  src/components/MypageAside/MyReview/Buttons/reviewWriteBtn.module.css
  src/components/MypageAside/ProfileInfo/ProfileInfo.tsx
  src/components/MypageAside/ProfileInfo/profileInfo.module.css
  src/components/MypageAside/ReviewWriteEdit/Button/Cancel/CancelBtn.tsx
  src/components/MypageAside/ReviewWriteEdit/Button/Register/RegisterBtn.tsx
  src/components/MypageAside/ReviewWriteEdit/ReviewWriteEdit.tsx
  src/components/MypageAside/ReviewWriteEdit/reviewWriteEdit.module.css
  src/components/MypageAside/SaveButton/SaveButton.tsx
  src/components/perfumes/BuyButton/BuyButton.tsx
  src/components/perfumes/DetailPage/BottomSheet/BottomSheet.tsx
  src/components/perfumes/DetailPage/BottomSheet/bottomSheet.module.css
  src/components/perfumes/DetailPage/DetailPage.tsx
  src/components/perfumes/DetailPage/detailPage.module.css
Labels: 🔴 P1: High, ✨ feature, 🛠️ enhancement, 😱 hard, 🎨 UI/UX, 💻 frontend

#110 ✨ feat: 리뷰 테스트를 위한 페이지 추가
  src/app/devtest/actiontest/reviewTest/ReviewEx.tsx
  src/app/devtest/actiontest/reviewTest/[id]/edit/page.tsx
  src/app/devtest/actiontest/reviewTest/[id]/page.tsx
Labels: ✨ feature, 🟢 P3: Medium, 💻 frontend, 😊 easy

#111 Feature/mirine
  src/app/mirine/page.module.css
  src/app/mirine/page.tsx
  src/app/perfumes/page.tsx
  src/components/perfumes/PerfumeItem/PerfumeItem.tsx
  src/components/perfumes/PerfumeItem/perfumeItem.module.css
  src/lib/clientFunction.ts
Labels: 🔴 P1: High, 😐 medium, ✨ feature, 💻 frontend

#114 Feature/aromashooter
  public/aromaShooter/aroma-cartridge.webp
  public/aromaShooter/aroma-shooter-bg.webp
  public/aromaShooter/aroma-shooter2.webp
  public/aromaShooter/aroma-shooter3.webp
  public/aromaShooter/intro-bg.webp
  public/aromaShooter/mirine-aromajoin.svg
  src/app/aroma-shooter/page.tsx
  src/components/AromaShooter/AromaCartridge.tsx
  src/components/AromaShooter/AromaShooterIntro.tsx
  src/components/AromaShooter/AromaShooterShop.tsx
  src/components/AromaShooter/Button/AromaShooterButton.tsx
  src/components/AromaShooter/Button/aromaShooterButton.module.css
  src/components/AromaShooter/MarqueeText.tsx
  src/components/AromaShooter/aromaCartridge.module.css
  src/components/AromaShooter/aromaShooterIntro.module.css
  src/components/AromaShooter/aromaShooterShop.module.css
  src/components/AromaShooter/marqueeText.module.css
Labels: 🔴 P1: High, 😐 medium, ✨ feature, 🎨 UI/UX, 💻 frontend

#116 Bugfix/aromashooter
  src/components/AromaShooter/aromaCartridge.module.css
Labels: 🛠️ enhancement, 🎨 UI/UX, 🔵 P4: Medium-Low, 🐛 bug, 💻 frontend, 😊 easy

#119 🐛 fix: 푸터 버그 수정
  src/components/common/Footer/Footer.tsx
Labels: 🔴 P1: High, 🎨 UI/UX, 🐛 bug, 💻 frontend, 😊 easy

#113 Test/patch review
  src/api/dbinit/team/data.json
  src/app/devtest/actiontest/reviewTest/OrderListEx.tsx
  src/app/devtest/actiontest/reviewTest/ReviewEx.tsx
  src/app/devtest/actiontest/reviewTest/[id]/ReviewInfoEx.tsx
  src/app/devtest/actiontest/reviewTest/[id]/edit/EditReviewContainerEx.tsx
  src/app/devtest/actiontest/reviewTest/[id]/edit/page.tsx
  src/app/devtest/actiontest/reviewTest/[id]/page.tsx
  src/app/devtest/actiontest/reviewTest/new/[id]/NewReviewContainerEx.tsx
  src/app/devtest/actiontest/reviewTest/new/[id]/ReviewFormEx.tsx
  src/app/devtest/actiontest/reviewTest/new/[id]/page.tsx
  src/app/devtest/actiontest/reviewTest/page.tsx
  src/lib/action.ts
  src/lib/clientFunction.ts
  src/lib/function.ts
Labels: ✅ test, 🟡 P2: Medium-High, 😱 hard, 🔗 API

#125 Feature/shopping cart
  src/app/shopping-cart/page.module.css
  src/app/shopping-cart/page.tsx
  src/components/ShoppingCart/CartControls/CartControls.jsx
  src/components/ShoppingCart/CartControls/CartControls.tsx
  src/components/ShoppingCart/CartControls/cartControls.module.css
  src/components/ShoppingCart/CartWithItem/CartWithItems.tsx
  src/components/ShoppingCart/CartWithItem/cartWithItems.module.css
  src/components/ShoppingCart/EmptyCart/EmptyCart.tsx
  src/components/ShoppingCart/EmptyCart/emptyCart.module.css
  src/components/ShoppingCart/PaymentButton/PaymentButton.tsx
  src/components/ShoppingCart/PaymentButton/payment.module.css
  src/components/ShoppingCart/ProductItem.tsx
  src/components/ShoppingCart/ProductItem/ProductItem.tsx
  src/components/ShoppingCart/ProductItem/productItem.module.css
  src/components/ui/Button/PrimaryButton.tsx
  src/components/ui/Button/SmallButton.tsx
  src/components/ui/Button/primaryButton.module.css
  src/components/ui/Button/smallButton.module.css
  src/components/ui/Container.tsx
  src/components/ui/container.module.css
Labels: ✨ feature, 🟢 P3: Medium, 🛠️ enhancement, 🎨 UI/UX, ♻️ refactor, 💻 frontend, 😊 easy

#127 Feature/mypage
  src/app/devtest/actiontest/page.tsx
  src/app/mypage/wishlist/page.tsx
  src/components/MypageAside/LikeList/LikeList.tsx
Labels: 🔴 P1: High, 🛠️ enhancement, 😱 hard, 💻 frontend

#135 Feature/mypage-UI
  public/image/perfume-test.webp
  src/components/MinineTest/ResultPage/PerfumeResult/PerfumeResult.tsx
  src/components/MypageAside/LikeList/likeList.module.css
  src/components/MypageAside/MyReview/MyReviewList/ReviewItem/ReviewItem.tsx
  src/components/MypageAside/MyReview/MyReviewList/myReviewList.module.css
  src/components/MypageAside/MyReview/MyReviewWriteList/MyReviewWriteList.tsx
  src/components/MypageAside/MyReview/MyReviewWriteList/myReviewWriteList.module.css
  src/components/MypageAside/TestResult/testResultPage.module.css
Labels: 🦁 chore, 🛠️ enhancement, 🎨 UI/UX, 💻 frontend, 🟣 P5: Low, 😊 easy

#138 readme.md 리팩토링
  README.md
Labels: 🛠️ enhancement, 🔵 P4: Medium-Low, 🐛 bug, ♻️ refactor, 📝 documentation, 😊 easy

#141 ♻️ refactor: DB init 데이터 수정
  src/api/dbinit/team/data.json
  src/api/dbinit/team/uploadFiles/mirine.webp
Labels: 🔴 P1: High, 🦁 chore, 💾 database, 📝 documentation, 😊 easy

#146 🐛 fix: 파일명 변경으로 모듈이 불러와지지 않는 현상 수정
  src/app/devtest/actiontest/Wishlist/MyLikeListPage.tsx
  src/app/mypage/layout.tsx
  src/components/layout/Sidebar/MypageSidebar.tsx
  src/components/pages/Mypage/LikeList/likeList.module.css
Labels: 🔴 P1: High, 🐛 bug, 💻 frontend, 🚀 deploy, 😊 easy

#147 3차 배포
  src/app/devtest/actiontest/Wishlist/MyLikeListPage.tsx
  src/app/mypage/layout.tsx
  src/components/layout/Sidebar/MypageSidebar.tsx
  src/components/pages/Mypage/LikeList/likeList.module.css
Labels: 🔴 P1: High, 🚀 deploy, 😊 easy

#153 feature/reviews page
  src/components/Review/List/List.tsx
  src/components/Review/List/list.module.css
  src/components/Review/ReviewCommon.tsx
  src/components/Review/reviewCommon.module.css
Labels: 🟡 P2: Medium-High, 🙋 help wanted, 🛠️ enhancement, 🎨 UI/UX, 💻 frontend

#154 Feature/user
  src/components/Login/LoginForm.tsx
  src/components/MinineTest/Header/Header.tsx
  src/components/MinineTest/Header/header.module.css
  src/components/SignUp/SignUpForm.tsx
  src/components/common/Header/Header.tsx
  src/components/common/Header/header.module.css
  src/lib/action.ts
  src/lib/clientFunction.ts
  src/store/userStore.ts
  src/types/user.ts
Labels: 🔴 P1: High, 😐 medium, ✨ feature, 💻 frontend

#160 Feature/home
  public/home/main-sld-aromashooter.webp
  public/home/main-sld-mirine.webp
  public/home/main-sld-review.webp
  public/home/review_1.webp
  public/home/review_10.webp
  public/home/review_11.webp
  public/home/review_2.webp
  public/home/review_3.webp
  public/home/review_4.webp
  public/home/review_5.webp
  public/home/review_6.webp
  public/home/review_7.webp
  public/home/review_8.webp
  public/home/review_9.webp
  src/components/pages/Home/MainVisualSlide.tsx
  src/components/pages/Home/ReviewSlide.tsx
  src/components/pages/Home/mainVisualSlide.module.css
Labels: 🔴 P1: High, 😐 medium, ✨ feature, 🎨 UI/UX, 💻 frontend

#162 ✨ feat: 찜 리스트 - LikeList 반응형 스타일링 및 마크업
  src/components/pages/Mypage/LikeList/LikeList.tsx
  src/components/pages/Mypage/LikeList/likeList.module.css
Labels: 🔴 P1: High, ✨ feature, 🎨 UI/UX, 💻 frontend, 😊 easy

#163 Feature/mirinetest page
  src/app/mirine-test/test/page.tsx
  src/components/MinineTest/Header/Header.tsx
  src/components/MinineTest/StartPage/TestStartPage.tsx
  src/components/MinineTest/StartPage/testStartPage.module.css
  src/components/MinineTest/TestPage/MirineTest.tsx
  src/components/MinineTest/TestPage/mirineTest.module.css
Labels: ✨ feature, 🟢 P3: Medium, 🛠️ enhancement, 🎨 UI/UX, 💻 frontend, 😊 easy

#166 feature/data
  src/api/dbinit/team/data.json
  src/api/dbinit/team/uploadFiles/review1.webp
  src/api/dbinit/team/uploadFiles/review10.webp
  src/api/dbinit/team/uploadFiles/review11.webp
  src/api/dbinit/team/uploadFiles/review12.webp
  src/api/dbinit/team/uploadFiles/review13.webp
  src/api/dbinit/team/uploadFiles/review14.webp
  src/api/dbinit/team/uploadFiles/review15.webp
  src/api/dbinit/team/uploadFiles/review16.webp
  src/api/dbinit/team/uploadFiles/review17.webp
  src/api/dbinit/team/uploadFiles/review18.webp
  src/api/dbinit/team/uploadFiles/review19.webp
  src/api/dbinit/team/uploadFiles/review2.webp
  src/api/dbinit/team/uploadFiles/review20.webp
  src/api/dbinit/team/uploadFiles/review21.webp
  src/api/dbinit/team/uploadFiles/review22.webp
  src/api/dbinit/team/uploadFiles/review23.webp
  src/api/dbinit/team/uploadFiles/review24.webp
  src/api/dbinit/team/uploadFiles/review25.webp
  src/api/dbinit/team/uploadFiles/review26.webp
  src/api/dbinit/team/uploadFiles/review27.webp
  src/api/dbinit/team/uploadFiles/review28.webp
  src/api/dbinit/team/uploadFiles/review29.webp
  src/api/dbinit/team/uploadFiles/review3.webp
  src/api/dbinit/team/uploadFiles/review30.webp
  src/api/dbinit/team/uploadFiles/review4.webp
  src/api/dbinit/team/uploadFiles/review5.webp
  src/api/dbinit/team/uploadFiles/review6.webp
  src/api/dbinit/team/uploadFiles/review7.webp
  src/api/dbinit/team/uploadFiles/review8.webp
  src/api/dbinit/team/uploadFiles/review9.webp
Labels: 🦁 chore, 💻 frontend, 🟣 P5: Low

#169 🐛 fix: 브랜드 오류 수정
  src/api/dbinit/team/data.json
  src/app/mirine/page.tsx
  src/app/perfumes/page.tsx
Labels: 🔴 P1: High, 🐛 bug, 💻 frontend, 😊 easy

#177 feature/test
  src/components/perfumes/DetailPage/BottomSheet/bottomSheet.module.css
Labels: 🦁 chore, 🎨 UI/UX, 🐛 bug, 💻 frontend, 😊 easy

#178 🐛 fix: 미리내 테스트 페이지 레이아웃 오류 수정 및 리펙토링
  src/app/mirine-test/layout.module.css
  src/app/mirine-test/layout.tsx
  src/components/MinineTest/Header/Header.tsx
  src/components/MinineTest/Header/header.module.css
  src/components/MinineTest/StartPage/TestStartPage.tsx
  src/components/MinineTest/StartPage/testStartPage.module.css
  src/components/MinineTest/TestPage/MirineTest.tsx
  src/components/MinineTest/TestPage/mirineTest.module.css
Labels: 😐 medium, 🟢 P3: Medium, 🎨 UI/UX, 🐛 bug, ♻️ refactor, 💻 frontend
